config/routes.rb
Rails.application.routes.draw do
  resources :students

  root 'welcome#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
      @students = Student.all
    end

  def show
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def edit
  @student = Student.find(params[:id])
  end

  def create
  @student = Student.new(student_params)

  @student.save
  redirect_to @student
  end

  def update
  @student = Student.find(params[:id])

  if @student.update(student_params)
    redirect_to @student
  else
    render 'edit'
  end
end

def destroy
  @student = Student.find(params[:id])
  @student.destroy

  redirect_to students_path
end

private
  def student_params
      params.require(:student).permit(:Name, :Weight, :Height, :colour, :GPA)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Students</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= form_for :student, url: students_path do |f| %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </p>

  <p>
    <%= f.label :Weight %><br>
    <%= f.text_field :Weight %>
  </p>

  <p>
    <%= f.label :Height %><br>
    <%= f.text_field :Height %>
  </p>

  <p>
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </p>

  <p>
    <%= f.label :GPA %><br>
    <%= f.text_field :GPA %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing Students</h1>

<%= link_to 'New student', new_student_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Weight</th>
    <th>Height</th>
    <th>colour</th>
    <th>GPA</th>
    <th colspan="3"></th>
  </tr>

  <% @students.each do |student| %>
    <tr>
      <td><%= student.Name %></td>
      <td><%= student.Weight %></td>
      <td><%= student.Height %></td>
      <td><%= student.colour %></td>
      <td><%= student.GPA %></td>
      <td><%= link_to 'Show', student_path(student) %></td>
     <td><%= link_to 'Edit', edit_student_path(student) %></td>
     <td><%= link_to 'Destroy', student_path(student),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/students/new.html.erb
<%= form_for :student, url: students_path do |f| %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </p>

  <p>
    <%= f.label :Weight %><br>
    <%= f.text_field :Weight %>
  </p>

  <p>
    <%= f.label :Height %><br>
    <%= f.text_field :Height %>
  </p>

  <p>
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </p>

  <p>
    <%= f.label :GPA %><br>
    <%= f.text_field :GPA %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<%= stylesheet_link_tag "calculator.css" %>


  <% @students.each do |student| %>
  <div id="box_display" style="width:<%= student.Weight %>px; height:<%= student.Height %>px">
      <p style="color:<%= student.colour %>"><%= student.Name %></p>
      <p><%= student.GPA %></p>
    </div>
  <% end %>


<%= link_to 'Back', students_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Students', controller: 'students' %>